[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_limit = 9223372036854775807
optimizer = true
optimizer_runs = 200
via_ir = false
solc_version = "0.8.23"

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 256 }

